### ISSUE TITLE
Console saying "Do Not have permission" when using a command

### ISSUE THREAD

**Issue by DinoNuggets2** [PintTheDragon/Images#2]
I'm trying to use this plugin, it dosen't say theres any errors or anything, and when i put the right command it, it says I dont have permission to do it, when I run the server.

**Comment by PintTheDragon** [comment]
Have you configured your permissions?

**Comment by DinoNuggets2** [comment]
I am not sure how.

**Comment by PintTheDragon** [comment]
Just because you don't know how to do something doesn't mean it's someone else's fault. This issue has nothing do with Images. Please go to EXILED.
